 <template>
    <div>
        <!-- Hero Section -->
        <div class="mb-10">
            <h1 class="text-4xl md:text-5xl font-bold mb-4">
                Project Structure
            </h1>
            <p class="text-xl text-gray-400 leading-relaxed">
                Understand the <strong class="text-primary-500">Khadem</strong> project architecture. 
                A clean, organized structure inspired by modern frameworks for scalability and maintainability.
            </p>
        </div>

        <!-- Overview Card -->
        <div class="bg-gradient-to-r from-blue-500/10 to-blue-600/5 border border-blue-500/20 rounded-lg p-6 mb-10">
            <div class="flex items-start gap-4">
                <div class="flex-shrink-0">
                    <i class="fas fa-folder-tree text-blue-500 text-3xl"></i>
                </div>
                <div>
                    <h3 class="text-lg font-semibold text-white mb-2">Well-Organized Architecture</h3>
                    <p class="text-gray-300 text-sm">
                        Every file and folder has a specific purpose, following Dart package conventions 
                        and modern backend best practices for easy navigation and maintenance.
                    </p>
                </div>
            </div>
        </div>

        <!-- Structure Overview -->
        <section class="mb-12">
            <h2 id="complete-structure" class="text-3xl font-bold mb-4">
                <i class="fas fa-sitemap text-primary-500 mr-2"></i>
                Complete Project Structure
            </h2>
            <p class="text-gray-300 mb-6">
                Here's the complete folder structure generated by <code class="px-1.5 py-0.5 bg-gray-800 rounded text-sm">khadem new</code>:
            </p>

            <CodeBlock :code="structureCode" language="text" />

            <div class="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="bg-gradient-to-br from-green-500/10 to-green-600/5 border border-green-500/20 rounded-lg p-5">
                    <div class="flex items-center gap-3 mb-3">
                        <div class="w-10 h-10 bg-green-500/20 rounded-lg flex items-center justify-center">
                            <i class="fas fa-code text-green-500"></i>
                        </div>
                        <h3 class="font-semibold text-white">Application Layer</h3>
                    </div>
                    <ul class="space-y-2 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-green-500 text-xs mt-1"></i>
                            <span><strong class="text-white">lib/app/</strong> — Business logic</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-green-500 text-xs mt-1"></i>
                            <span><strong class="text-white">lib/core/</strong> — Kernel & bootstrap</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-green-500 text-xs mt-1"></i>
                            <span><strong class="text-white">lib/routes/</strong> — Route definitions</span>
                        </li>
                    </ul>
                </div>

                <div class="bg-gradient-to-br from-blue-500/10 to-blue-600/5 border border-blue-500/20 rounded-lg p-5">
                    <div class="flex items-center gap-3 mb-3">
                        <div class="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                            <i class="fas fa-database text-blue-500"></i>
                        </div>
                        <h3 class="font-semibold text-white">Data Layer</h3>
                    </div>
                    <ul class="space-y-2 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-blue-500 text-xs mt-1"></i>
                            <span><strong class="text-white">lib/database/</strong> — Migrations & seeders</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-blue-500 text-xs mt-1"></i>
                            <span><strong class="text-white">storage/</strong> — File storage & cache</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-blue-500 text-xs mt-1"></i>
                            <span><strong class="text-white">lang/</strong> — Translations</span>
                        </li>
                    </ul>
                </div>

                <div class="bg-gradient-to-br from-purple-500/10 to-purple-600/5 border border-purple-500/20 rounded-lg p-5">
                    <div class="flex items-center gap-3 mb-3">
                        <div class="w-10 h-10 bg-purple-500/20 rounded-lg flex items-center justify-center">
                            <i class="fas fa-cog text-purple-500"></i>
                        </div>
                        <h3 class="font-semibold text-white">Configuration</h3>
                    </div>
                    <ul class="space-y-2 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-purple-500 text-xs mt-1"></i>
                            <span><strong class="text-white">config/</strong> — Environment settings</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-purple-500 text-xs mt-1"></i>
                            <span><strong class="text-white">.env</strong> — Environment variables</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-chevron-right text-purple-500 text-xs mt-1"></i>
                            <span><strong class="text-white">pubspec.yaml</strong> — Dependencies</span>
                        </li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- lib/ Directory -->
        <section class="mb-12">
            <h2 id="lib-directory" class="text-3xl font-bold mb-4">
                <i class="fas fa-folder-open text-primary-500 mr-2"></i>
                The lib/ Directory
            </h2>
            <p class="text-gray-300 mb-6">
                The core of your Dart application following modern package conventions. 
                All source code lives within <code class="px-1.5 py-0.5 bg-gray-800 rounded text-sm">lib/</code>.
            </p>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <!-- HTTP Layer -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <div class="flex items-center gap-3 mb-4">
                        <div class="w-10 h-10 bg-green-500/20 rounded-lg flex items-center justify-center">
                            <i class="fas fa-globe text-green-500"></i>
                        </div>
                        <div>
                            <h3 class="font-semibold text-white text-lg">HTTP Layer</h3>
                            <p class="text-xs text-gray-400">Request handling & middleware</p>
                        </div>
                    </div>
                    <ul class="space-y-3 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">controllers/</strong>
                                <p class="text-xs text-gray-400">Route handlers for requests</p>
                            </div>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">middleware/</strong>
                                <p class="text-xs text-gray-400">Auth, CORS, logging filters</p>
                            </div>
                        </li>
                    </ul>
                </div>

                <!-- Domain Layer -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <div class="flex items-center gap-3 mb-4">
                        <div class="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                            <i class="fas fa-box text-blue-500"></i>
                        </div>
                        <div>
                            <h3 class="font-semibold text-white text-lg">Domain Layer</h3>
                            <p class="text-xs text-gray-400">Business logic & models</p>
                        </div>
                    </div>
                    <ul class="space-y-3 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">models/</strong>
                                <p class="text-xs text-gray-400">Database entities & relationships</p>
                            </div>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">providers/</strong>
                                <p class="text-xs text-gray-400">Service providers & DI</p>
                            </div>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">jobs/</strong>
                                <p class="text-xs text-gray-400">Background queue jobs</p>
                            </div>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-folder text-primary-500 text-xs mt-1"></i>
                            <div>
                                <strong class="text-white">listeners/</strong>
                                <p class="text-xs text-gray-400">Event listeners</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="mt-6">
                <CodeBlock :code="appStructureCode" language="text" />
            </div>
        </section>

        <!-- Routes Directory -->
        <section class="mb-12">
            <h2 id="routes-directory" class="text-3xl font-bold mb-4">
                <i class="fas fa-route text-primary-500 mr-2"></i>
                Routes Directory
            </h2>
            <p class="text-gray-300 mb-6">
                Define all application routes organized by protocol type.
            </p>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                <div class="p-5 bg-gradient-to-br from-green-500/10 to-green-600/5 border border-green-500/20 rounded-lg">
                    <div class="flex items-center gap-3 mb-2">
                        <i class="fas fa-file-code text-green-500 text-xl"></i>
                        <h3 class="font-semibold text-white">web.dart</h3>
                    </div>
                    <p class="text-sm text-gray-300">HTTP routes for REST API endpoints</p>
                </div>

                <div class="p-5 bg-gradient-to-br from-blue-500/10 to-blue-600/5 border border-blue-500/20 rounded-lg">
                    <div class="flex items-center gap-3 mb-2">
                        <i class="fas fa-plug text-blue-500 text-xl"></i>
                        <h3 class="font-semibold text-white">socket.dart</h3>
                    </div>
                    <p class="text-sm text-gray-300">WebSocket routes for real-time communication</p>
                </div>
            </div>

            <CodeBlock :code="routesExample" language="dart" />
        </section>

        <!-- Config Directory -->
        <section class="mb-12">
            <h2 id="config-directory" class="text-3xl font-bold mb-4">
                <i class="fas fa-sliders-h text-primary-500 mr-2"></i>
                Configuration
            </h2>
            <p class="text-gray-300 mb-6">
                Environment-specific configuration files merged with environment variables.
            </p>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                <div class="p-4 bg-gray-800/50 border border-gray-700 rounded-lg">
                    <div class="flex items-center gap-2 mb-2">
                        <i class="fas fa-file-code text-primary-500"></i>
                        <h3 class="font-semibold text-white text-sm">app.dart</h3>
                    </div>
                    <p class="text-xs text-gray-400">Main app configuration</p>
                </div>

                <div class="p-4 bg-gray-800/50 border border-gray-700 rounded-lg">
                    <div class="flex items-center gap-2 mb-2">
                        <i class="fas fa-folder text-green-500"></i>
                        <h3 class="font-semibold text-white text-sm">development/</h3>
                    </div>
                    <p class="text-xs text-gray-400">Dev environment settings</p>
                </div>

                <div class="p-4 bg-gray-800/50 border border-gray-700 rounded-lg">
                    <div class="flex items-center gap-2 mb-2">
                        <i class="fas fa-folder text-blue-500"></i>
                        <h3 class="font-semibold text-white text-sm">production/</h3>
                    </div>
                    <p class="text-xs text-gray-400">Production settings</p>
                </div>
            </div>

            <CodeBlock :code="configExample" language="dart" />
        </section>

        <!-- Key Directories Grid -->
        <section class="mb-12">
            <h2 class="text-3xl font-bold mb-6">
                <i class="fas fa-layer-group text-primary-500 mr-2"></i>
                Key Directories
            </h2>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <!-- Core Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="core-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-cubes text-purple-500 mr-2"></i>
                        lib/core/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        Application kernel handling bootstrapping, service registration, and framework setup.
                    </p>
                    <div class="text-xs text-gray-400">
                        <strong class="text-white">Key file:</strong> kernel.dart
                    </div>
                </div>

                <!-- Database Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="database-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-database text-blue-500 mr-2"></i>
                        lib/database/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        Database migrations and seeders for schema management.
                    </p>
                    <ul class="text-xs text-gray-400 space-y-1">
                        <li>• <strong class="text-white">migrations/</strong> — Schema changes</li>
                        <li>• <strong class="text-white">seeders/</strong> — Test data</li>
                    </ul>
                </div>

                <!-- Storage Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="storage-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-hdd text-green-500 mr-2"></i>
                        storage/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        File storage system for application files, cache, and logs.
                    </p>
                    <ul class="text-xs text-gray-400 space-y-1">
                        <li>• <strong class="text-white">app/</strong> — App files</li>
                        <li>• <strong class="text-white">cache/</strong> — Cache data</li>
                        <li>• <strong class="text-white">logs/</strong> — Log files</li>
                    </ul>
                </div>

                <!-- Lang Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="lang-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-language text-yellow-500 mr-2"></i>
                        lang/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        Localization files for multi-language support.
                    </p>
                    <ul class="text-xs text-gray-400 space-y-1">
                        <li>• <strong class="text-white">ar/</strong> — Arabic translations</li>
                        <li>• <strong class="text-white">en/</strong> — English translations</li>
                    </ul>
                </div>

                <!-- Public Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="public-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-globe text-cyan-500 mr-2"></i>
                        public/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        Publicly accessible static files served directly.
                    </p>
                    <ul class="text-xs text-gray-400 space-y-1">
                        <li>• <strong class="text-white">assets/</strong> — CSS, JS, images</li>
                    </ul>
                </div>

                <!-- Resources Directory -->
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="resources-directory" class="font-semibold text-white mb-3 flex items-center text-lg">
                        <i class="fas fa-file-alt text-orange-500 mr-2"></i>
                        resources/
                    </h3>
                    <p class="text-sm text-gray-300 mb-3">
                        Application resources and view templates.
                    </p>
                    <ul class="text-xs text-gray-400 space-y-1">
                        <li>• <strong class="text-white">views/</strong> — Template files</li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- Entry Points -->
        <section class="mb-12">
            <h2 class="text-3xl font-bold mb-6">
                <i class="fas fa-door-open text-primary-500 mr-2"></i>
                Entry Points
            </h2>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="main-entry" class="font-semibold text-white mb-3 flex items-center">
                        <i class="fas fa-file-code text-green-500 mr-2"></i>
                        lib/main.dart
                    </h3>
                    <p class="text-sm text-gray-300">
                        Main application entry point for bootstrapping and server startup.
                    </p>
                </div>

                <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                    <h3 id="bin-directory" class="font-semibold text-white mb-3 flex items-center">
                        <i class="fas fa-terminal text-blue-500 mr-2"></i>
                        bin/
                    </h3>
                    <p class="text-sm text-gray-300">
                        CLI entry points and command-line scripts.
                    </p>
                </div>
            </div>
        </section>

        <!-- Configuration Files -->
        <section class="mb-12">
            <h2 id="configuration-files" class="text-3xl font-bold mb-6">
                <i class="fas fa-cog text-primary-500 mr-2"></i>
                Configuration Files
            </h2>

            <div class="space-y-6">
                <!-- pubspec.yaml -->
                <div>
                    <div class="flex items-center gap-2 mb-3">
                        <i class="fas fa-file-code text-purple-500 text-xl"></i>
                        <h3 class="font-semibold text-white text-lg">pubspec.yaml</h3>
                    </div>
                    <p class="text-sm text-gray-300 mb-4">Dart project configuration and dependencies</p>
                    <CodeBlock :code="pubspecExample" language="yaml" />
                </div>

                <!-- .env -->
                <div>
                    <div class="flex items-center gap-2 mb-3">
                        <i class="fas fa-key text-green-500 text-xl"></i>
                        <h3 class="font-semibold text-white text-lg">.env</h3>
                    </div>
                    <p class="text-sm text-gray-300 mb-4">Environment variables (never commit this!)</p>
                    <CodeBlock :code="envExample" language="properties" />
                </div>
            </div>
        </section>

        <!-- Best Practices -->
        <section class="mb-12">
            <h2 id="best-practices" class="text-3xl font-bold mb-6">
                <i class="fas fa-check-circle text-primary-500 mr-2"></i>
                Best Practices
            </h2>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="bg-gradient-to-br from-green-500/10 to-green-600/5 border border-green-500/20 rounded-lg p-6">
                    <h3 class="font-semibold text-white mb-4 flex items-center text-lg">
                        <i class="fas fa-thumbs-up text-green-500 mr-2"></i>
                        Do's
                    </h3>
                    <ul class="space-y-3 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-check text-green-500 text-xs mt-1"></i>
                            <span>Keep controllers thin, delegate to services</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-check text-green-500 text-xs mt-1"></i>
                            <span>Use meaningful names for files and directories</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-check text-green-500 text-xs mt-1"></i>
                            <span>Group related functionality together</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-check text-green-500 text-xs mt-1"></i>
                            <span>Follow single responsibility principle</span>
                        </li>
                    </ul>
                </div>

                <div class="bg-gradient-to-br from-red-500/10 to-red-600/5 border border-red-500/20 rounded-lg p-6">
                    <h3 class="font-semibold text-white mb-4 flex items-center text-lg">
                        <i class="fas fa-thumbs-down text-red-500 mr-2"></i>
                        Don'ts
                    </h3>
                    <ul class="space-y-3 text-sm text-gray-300">
                        <li class="flex items-start gap-2">
                            <i class="fas fa-times text-red-500 text-xs mt-1"></i>
                            <span>Put business logic in controllers</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-times text-red-500 text-xs mt-1"></i>
                            <span>Create deep directory nesting</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-times text-red-500 text-xs mt-1"></i>
                            <span>Mix different concerns in one file</span>
                        </li>
                        <li class="flex items-start gap-2">
                            <i class="fas fa-times text-red-500 text-xs mt-1"></i>
                            <span>Hardcode configuration values</span>
                        </li>
                    </ul>
                </div>
            </div>
        </section>

        <!-- Customization -->
        <section class="mb-12">
            <h2 id="customizing-structure" class="text-3xl font-bold mb-6">
                <i class="fas fa-wrench text-primary-500 mr-2"></i>
                Customizing the Structure
            </h2>
            <p class="text-gray-300 mb-6">
                While Khadem provides a solid foundation, you can customize it to fit your needs.
            </p>

            <div class="bg-gradient-to-r from-yellow-500/10 to-yellow-600/5 border border-yellow-500/20 rounded-lg p-5 mb-6">
                <div class="flex items-start gap-3">
                    <i class="fas fa-exclamation-triangle text-yellow-500 text-xl mt-0.5"></i>
                    <div>
                        <h3 class="font-semibold text-white mb-1">Important</h3>
                        <p class="text-sm text-gray-300">
                            When customizing, update imports and service registrations in 
                            <code class="px-1.5 py-0.5 bg-gray-900 rounded text-xs">lib/core/kernel.dart</code>.
                        </p>
                    </div>
                </div>
            </div>

            <div class="bg-gray-800/50 border border-gray-700 rounded-lg p-6">
                <h3 class="font-semibold text-white mb-4">Example: Adding Custom Directories</h3>
                <CodeBlock :code="customStructureExample" language="text" />
            </div>
        </section>


        <!-- Help Section -->
        <div class="bg-gradient-to-r from-primary-500/10 to-purple-500/10 border border-primary-500/20 rounded-lg p-6">
            <div class="flex items-start gap-4">
                <div class="flex-shrink-0">
                    <i class="fas fa-question-circle text-primary-500 text-3xl"></i>
                </div>
                <div>
                    <h3 class="text-xl font-semibold text-white mb-2">Questions about Structure?</h3>
                    <p class="text-gray-300 mb-4">
                        Join our community to discuss project organization and best practices.
                    </p>
                    <div class="flex flex-wrap gap-3">
                        <a 
                            href="https://github.com/khedrmahmoud/khadem/discussions" 
                            target="_blank" 
                            rel="noopener noreferrer" 
                            class="inline-flex items-center px-4 py-2 bg-blue-500/20 hover:bg-blue-500/30 text-blue-400 rounded-lg transition-colors text-sm font-medium"
                        >
                            <i class="fas fa-comments mr-2"></i>
                            Join Discussion
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
definePageMeta({ layout: 'docs' })
useHead({ 
    title: 'Project Structure - Khadem Docs',
    meta: [
        {
            name: 'description',
            content: 'Comprehensive guide to Khadem project structure - Learn about directories, files, and architecture patterns for building scalable Dart backend applications.'
        }
    ]
})

const structureCode = `my_api/
├── lib/
│   ├── main.dart               # Application entry point
│   ├── app/
│   │   ├── http/
│   │   ├── jobs/
│   │   ├── listeners/
│   │   ├── observers/
│   │   ├── models/
│   │   └── providers/
│   ├── config/ # Application configuration
│   ├── core/
│   │   └── kernel.dart        # Application kernel
│   ├── database/
│   └── routes/
│       ├── socket.dart
│       └── web.dart
├── config/
├── lang/
│   ├── ar/
│   └── en/
├── public/
├── resources/
├── storage/
├── tests/                      # Test files
├── .env                        # Environment variables
├── .gitignore                  # Git ignore rules
├── pubspec.yaml                # Package configuration
└── pubspec.lock                # Package lock file`;

const appStructureCode = `lib/app/
├── http/
│   ├── controllers/
│   │   ├── home_controller.dart
│   │   ├── user_controller.dart
│   │   └── api/
│   │       └── v1/
│   │           └── auth_controller.dart
│   └── middleware/
│       ├── auth_middleware.dart
│       ├── cors_middleware.dart
│       └── logging_middleware.dart
├── models/
│   ├── user.dart
│   └── post.dart
├── providers/
│   ├── app_service_provider.dart
│   ├── event_service_provider.dart
│   └── scheduler_service_provider.dart
├── jobs/
│   ├── send_welcome_email_job.dart
│   ├── process_image_job.dart
│   └── email/
│       └── send_notification_job.dart
├── listeners/
│   └── user_registered_listener.dart
├── observers/
│   └── user_registered_observer.dart`

const routesExample = `// lib/routes/web.dart
import 'package:khadem/khadem_dart.dart';
import '../app/http/controllers/home_controller.dart';
import '../core/kernel.dart';

void registerRoutes(Server server) {
  // Register global middlewares
  server.useMiddlewares(Kernel.middlewares);

  // API Routes
  server.group(
    prefix: '/api',
    middleware: [],
    routes: (router) async {
      router.get('/hello', HomeController.index);
      router.get('/welcome', HomeController.welcome);
      router.get('/stream', HomeController.stream);
    },
  );

  // Serve static files
  server.serveStatic();
}

// routes/socket.dart
import 'package:khadem/khadem_dart.dart';

void registerSocketRoutes(SocketServer socketServer) {
  socketServer.on('chat:message', (socket, data) {
    // Handle chat messages
    socketServer.broadcast('chat:message', data);
  });

  socketServer.on('user:join', (socket, data) {
    // Handle user joining
    socket.broadcast('user:joined', data);
  });
}`

const configExample = `// config/app.dart
import 'package:khadem/khadem_dart.dart';

class AppConfig {
  static final env = Khadem.env;

  static Map<String, Map<String, dynamic>> get configs => {
    'database': {
      'driver': env.getOrDefault('DB_CONNECTION', 'mysql'),
      'host': env.getOrDefault('DB_HOST', 'localhost'),
      'port': env.getInt('DB_PORT'),
      'database': env.get('DB_DATABASE'),
      'username': env.get('DB_USERNAME'),
      'password': env.get('DB_PASSWORD'),
      'run_migrations': true,
      'run_seeders': false,
    },
    ... // Other configurations
  };
`

const kernelExample = `// lib/core/kernel.dart
import 'package:khadem/khadem_dart.dart';
import '../app/providers/app_service_provider.dart';
import '../app/providers/event_service_provider.dart';
import '../app/providers/scheduler_service_provider.dart';
import '../../config/app.dart';
import '../database/migrations/migrations.dart';

class Kernel {
  Kernel._();

  static List<ServiceProvider> get coreProviders => [
    QueueServiceProvider(),
    AuthServiceProvider(),
    DatabaseServiceProvider(),
  ];

  static List<ServiceProvider> get applicationProviders => [
    AppServiceProvider(),
    EventServiceProvider(),
    SchedulerServiceProvider(),
  ];

  static List<ServiceProvider> get allProviders => [
    ...coreProviders,
    ...applicationProviders,
  ];

  static List<Middleware> get middlewares => [
    CorsMiddleware(),
    LoggingMiddleware(),
    SetLocaleMiddleware(),
  ];

  static final Map<String, Map<String, dynamic>> configs = AppConfig.configs;
  static List<MigrationFile> get migrations => migrationsFiles;

  static Future<void> bootstrap() async {
    await Khadem.registerCoreServices();
    Khadem.register(allProviders);
    Khadem.loadConfigs(configs);
    await Khadem.boot();

    if (configs['database']?['run_migrations'] == true) {
      await Khadem.migrator.upAll(migrations);
    }
  }
}`

const databaseStructureCode = `lib/database/
├── migrations/
│   ├── 001_create_users_table.dart
│   ├── 002_create_posts_table.dart
│   ├── 003_add_user_id_to_posts.dart
│   └── migrations.dart
└── seeders/
    ├── database_seeder.dart
    ├── user_seeder.dart
    └── post_seeder.dart`

const storageStructureCode = `storage/
├── app/
│   ├── public/
│   └── private/
├── framework/
│   ├── cache/
│   │   ├── data/
│   │   └── views/
│   ├── sessions/
│   └── views/
└── logs/
    ├── khadem.log
    └── error.log`

const mainEntryPoint = `// lib/main.dart
import 'dart:async';
import 'dart:io';
import 'package:khadem/khadem_dart.dart';
import 'lib/core/kernel.dart';
import '../routes/socket.dart';
import '../routes/web.dart';

Future<void> main(List<String> args) async {
  if (_isSnapshotBuild()) return;

  final container = Khadem.container;
  await Kernel.bootstrap();

  final port = _extractPort(args) ?? Khadem.env.getInt("APP_PORT", defaultValue: 8080);

  await Future.wait([
    _startHttpServer(port, container),
    _startSocketServer(container, Khadem.socket),
  ]);
}

bool _isSnapshotBuild() => Platform.environment.containsKey('KHADIM_JIT_TRAINING');

Future _startHttpServer(int port, ContainerInterface container) async {
  final server = Server();
  registerRoutes(server);
  server.setInitializer(() async {
    registerRoutes(server);
    await server.start(port: port);
  });
  await server.reload();
}

Future<void> _startSocketServer(container, manager) async {
  final socketPort = Khadem.env.getInt("SOCKET_PORT", defaultValue: 8080);
  final socketServer = SocketServer(socketPort, manager: manager);
  registerSocketRoutes(socketServer);
  await socketServer.start();
}

int? _extractPort(List<String> args) {
  final portIndex = args.indexOf('--port');
  if (portIndex != -1 && args.length > portIndex + 1) {
    return int.tryParse(args[portIndex + 1]);
  }
  return null;
}`

const serverEntryPoint = `// lib/main.dart
import '../lib/main.dart' as app;

Future<void> main(List<String> args) async {
  await app.main(args);
}`

const pubspecExample = `name: my_api
description: A new Khadem Dart project.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  khadem:
    path: ../khadem

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.6`

const envExample = `# Application Configuration
APP_NAME=MyFirstAPI
APP_ENV=development
APP_PORT=8080
APP_LOCALE=en

# Database Configuration (MySQL)
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=my_first_api_db
DB_USERNAME=root
DB_PASSWORD=

# JWT Authentication
JWT_SECRET="your-super-secret-jwt-key-here"
JWT_ACCESS_EXPIRY_MINUTES=60
JWT_REFRESH_EXPIRY_DAYS=30`

const gitignoreExample = `# Dart
.dart_tool/
.packages
pubspec.lock

# Environment variables
.env
.env.local
.env.*.local

# Build outputs
build/
.dart_tool/

# IDEs
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
tmp/
temp/

# Test coverage
coverage/

# Khadem specific
storage/framework/cache/*
storage/framework/sessions/*
storage/framework/views/*
storage/logs/*`

const customStructureExample = `my_api/
├── lib/
│   ├── app/
│   │   ├── http/
│   │   ├── services/
│   │   │   ├── payment/
│   │   │   │   ├── stripe_service.dart
│   │   │   │   └── paypal_service.dart
│   │   │   └── notification/
│   │   │       ├── email_service.dart
│   │   │       └── sms_service.dart
│   │   └── repositories/
│   │       ├── user_repository.dart
│   │       └── post_repository.dart
│   ├── core/
│   └── database/
├── config/
│   ├── payment.dart
│   └── notification.dart
└── tests/
    ├── unit/
    │   ├── services/
    │   └── repositories/
    └── feature/
        ├── payment/
        └── notification/`
</script>