 <template>
    <div>
        <h1>Project Structure</h1>

        <p class="mb-6 text-lg">
            Khadem projects follow a clean, organized structure inspired by Laravel. When you create a new project using the Khadem CLI, it generates a complete folder structure designed for scalability, maintainability, and modern development practices.
        </p>

        <div class="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg p-6 mb-8">
            <div class="flex items-center">
                <div class="text-2xl mr-3">📁</div>
                <div>
                    <h3 class="font-semibold text-blue-800 dark:text-blue-200">Well-Organized Structure</h3>
                    <p class="text-blue-700 dark:text-blue-300 text-sm">
                        Every file and folder has a specific purpose, making your codebase easy to navigate and maintain.
                    </p>
                </div>
            </div>
        </div>

        <h2 id="complete-structure">Complete Project Structure</h2>
        <p class="mb-4">Here's the complete folder structure generated by <code>khadem new</code>:</p>

        <CodeBlock :code="structureCode" language="text" />

        <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
            <div class="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                <h3 class="font-semibold mb-3 flex items-center">
                    <span class="text-green-600 mr-2">📂</span> Application Layer
                </h3>
                <ul class="space-y-2 text-sm">
                    <li><strong>lib/app/</strong> - Business logic and domain code</li>
                    <li><strong>lib/core/</strong> - Application kernel and bootstrap</li>
                    <li><strong>routes/</strong> - HTTP and WebSocket route definitions</li>
                    <li><strong>config/</strong> - Environment-specific configurations</li>
                </ul>
            </div>

            <div class="border border-gray-200 dark:border-gray-700 rounded-lg p-4">
                <h3 class="font-semibold mb-3 flex items-center">
                    <span class="text-blue-600 mr-2">🗄️</span> Data & Storage
                </h3>
                <ul class="space-y-2 text-sm">
                    <li><strong>lib/database/</strong> - Migrations and database seeders</li>
                    <li><strong>storage/</strong> - File storage and cache directories</li>
                    <li><strong>lang/</strong> - Localization files</li>
                    <li><strong>resources/</strong> - Views and assets</li>
                </ul>
            </div>
        </div>

        <h2 id="lib-directory">lib/ Directory</h2>
        <p class="mb-4">
            The core of your Dart application, following modern Dart package conventions. All application code lives within the <code>lib/</code> directory.
        </p>

        <h3>lib/app/ Directory</h3>
        <p class="mb-4">
            The heart of your application. Contains all business logic, domain models, and application services.
        </p>

        <h3>HTTP Layer</h3>
        <p class="mb-4">Handles web requests, responses, and HTTP-specific logic:</p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>controllers/</strong> - Route handlers that process requests and return responses</li>
            <li><strong>middleware/</strong> - Request/response filters (auth, CORS, logging, etc.)</li>
        </ul>

        <h3>Domain Layer</h3>
        <p class="mb-4">Core business logic and data models:</p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>models/</strong> - Database entity representations with relationships</li>
            <li><strong>providers/</strong> - Service providers for dependency injection</li>
            <li><strong>jobs/</strong> - Background job classes for queue processing</li>
            <li><strong>listeners/</strong> - Event listeners for async processing</li>
        </ul>

        <CodeBlock :code="appStructureCode" language="text" />

        <h2 id="routes-directory">routes/ Directory</h2>
        <p class="mb-4">
            Define all your application routes here. Routes are organized by protocol and purpose:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>web.dart</strong> - HTTP routes for web endpoints</li>
            <li><strong>socket.dart</strong> - WebSocket routes for real-time communication</li>
        </ul>

        <CodeBlock :code="routesExample" language="dart" />

        <h2 id="config-directory">config/ Directory</h2>
        <p class="mb-4">
            Environment-specific configuration files. Each file exports configuration maps that are merged with environment variables:
        </p>

        <h3>Configuration Structure</h3>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>app.dart</strong> - Main application configuration</li>
            <li><strong>development/</strong> - Development-specific settings</li>
            <li><strong>production/</strong> - Production-specific settings</li>
        </ul>

        <CodeBlock :code="configExample" language="dart" />

        <h2 id="core-directory">lib/core/ Directory</h2>
        <p class="mb-4">
            Contains the application kernel that handles bootstrapping, service registration, and core framework setup:
        </p>

        <CodeBlock :code="kernelExample" language="dart" />

        <h2 id="database-directory">lib/database/ Directory</h2>
        <p class="mb-4">
            Database-related files including migrations and seeders:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>migrations/</strong> - Database schema changes and migrations.dart registry</li>
            <li><strong>seeders/</strong> - Database seeding scripts</li>
        </ul>

        <CodeBlock :code="databaseStructureCode" language="text" />

        <h2 id="storage-directory">storage/ Directory</h2>
        <p class="mb-4">
            File storage system with organized subdirectories:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>app/</strong> - Application-specific files</li>
            <li><strong>framework/</strong> - Framework cache, sessions, and views</li>
            <li><strong>logs/</strong> - Application log files</li>
        </ul>

        <CodeBlock :code="storageStructureCode" language="text" />

        <h2 id="lang-directory">lang/ Directory</h2>
        <p class="mb-4">
            Localization files for multi-language support:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>ar/</strong> - Arabic language files</li>
            <li><strong>en/</strong> - English language files</li>
        </ul>

        <h2 id="public-directory">public/ Directory</h2>
        <p class="mb-4">
            Publicly accessible files served directly by the web server:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>index.html</strong> - Default HTML page</li>
            <li><strong>assets/</strong> - Static assets (CSS, JS, images)</li>
        </ul>

        <h2 id="resources-directory">resources/ Directory</h2>
        <p class="mb-4">
            Application resources like views and templates:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>views/</strong> - Template files for rendering</li>
        </ul>

        <h2 id="main-entry">lib/main.dart</h2>
        <p class="mb-4">
            The main application entry point following Dart package conventions:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>lib/main.dart</strong> - Application bootstrap and server startup</li>
        </ul>

        <CodeBlock :code="mainEntryPoint" language="dart" />

        <h2 id="bin-directory">bin/ Directory</h2>
        <p class="mb-4">
            CLI entry points and command-line scripts:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li><strong>server.dart</strong> - CLI wrapper for the main application</li>
        </ul>

        <CodeBlock :code="serverEntryPoint" language="dart" />

        <h2 id="tests-directory">tests/ Directory</h2>
        <p class="mb-4">
            Unit and integration tests for your application:
        </p>
        <ul class="list-disc pl-6 mb-6 space-y-2">
            <li>Unit tests for individual components</li>
            <li>Integration tests for full workflows</li>
            <li>Test utilities and mocks</li>
        </ul>

        <h2 id="configuration-files">Configuration Files</h2>

        <h3>pubspec.yaml</h3>
        <p class="mb-4">Dart project configuration and dependencies:</p>
        <CodeBlock :code="pubspecExample" language="yaml" />

        <h3>.env</h3>
        <p class="mb-4">Environment variables for configuration:</p>
        <CodeBlock :code="envExample" language="properties" />

        <h3>.gitignore</h3>
        <p class="mb-4">Git ignore patterns for Dart/Khadem projects:</p>
        <CodeBlock :code="gitignoreExample" language="text" />

        <h2 id="best-practices">Best Practices</h2>

        <div class="space-y-4 mb-8">
            <div class="border border-green-200 dark:border-green-800 rounded-lg p-4">
                <h3 class="font-semibold text-green-800 dark:text-green-200 mb-2">✅ Do's</h3>
                <ul class="text-green-700 dark:text-green-300 text-sm space-y-1">
                    <li>• Keep controllers thin and delegate to services</li>
                    <li>• Use meaningful names for files and directories</li>
                    <li>• Group related functionality together</li>
                    <li>• Follow the single responsibility principle</li>
                </ul>
            </div>

            <div class="border border-red-200 dark:border-red-800 rounded-lg p-4">
                <h3 class="font-semibold text-red-800 dark:text-red-200 mb-2">❌ Don'ts</h3>
                <ul class="text-red-700 dark:text-red-300 text-sm space-y-1">
                    <li>• Don't put business logic in controllers</li>
                    <li>• Don't create deep directory nesting</li>
                    <li>• Don't mix different concerns in one file</li>
                    <li>• Don't hardcode configuration values</li>
                </ul>
            </div>
        </div>

        <h2 id="customizing-structure">Customizing the Structure</h2>
        <p class="mb-4">
            While Khadem provides a solid foundation, you can customize the structure to fit your needs:
        </p>

        <div class="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-4 mb-6">
            <h3 class="font-semibold text-yellow-800 dark:text-yellow-200 mb-2">⚠️ Important</h3>
            <p class="text-yellow-700 dark:text-yellow-300 text-sm">
                When customizing the structure, ensure you update the corresponding imports and service registrations in <code>lib/core/kernel.dart</code>.
            </p>
        </div>

        <h3>Adding New Directories</h3>
        <p class="mb-4">You can add custom directories for specific functionality:</p>
        <CodeBlock :code="customStructureExample" language="text" />

        <h2 id="next-steps">Next Steps</h2>
        <p class="mb-4">Now that you understand the project structure:</p>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
            <NuxtLink to="/docs/getting-started/creating-project" class="block p-4 border border-primary-200 dark:border-primary-800 rounded-lg hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-colors">
                <div class="flex items-center">
                    <div class="text-2xl mr-3">🚀</div>
                    <div>
                        <h3 class="font-semibold text-primary-800 dark:text-primary-200">Create Your First Project</h3>
                        <p class="text-sm text-primary-600 dark:text-primary-300">Hands-on guide to creating your first Khadem app</p>
                    </div>
                </div>
            </NuxtLink>

            <NuxtLink to="/docs/getting-started/configuration" class="block p-4 border border-primary-200 dark:border-primary-800 rounded-lg hover:bg-primary-50 dark:hover:bg-primary-900/20 transition-colors">
                <div class="flex items-center">
                    <div class="text-2xl mr-3">⚙️</div>
                    <div>
                        <h3 class="font-semibold text-primary-800 dark:text-primary-200">Configuration</h3>
                        <p class="text-sm text-primary-600 dark:text-primary-300">Learn about environment and app configuration</p>
                    </div>
                </div>
            </NuxtLink>
        </div>
    </div>
</template>

<script setup>
definePageMeta({ layout: 'docs' })
useHead({ title: 'Project Structure - Khadem Docs' })

const structureCode = `my_api/
├── lib/
│   ├── app/
│   │   ├── http/
│   │   │   ├── controllers/
│   │   │   │   └── home_controller.dart
│   │   │   └── middleware/
│   │   │       └── cors_middleware.dart
│   │   ├── jobs/
│   │   ├── listeners/
│   │   ├── models/
│   │   └── providers/
│   │       ├── app_service_provider.dart
│   │       ├── event_service_provider.dart
│   │       └── scheduler_service_provider.dart
│   ├── core/
│   │   └── kernel.dart
│   ├── database/
│   │   ├── migrations/
│   │   └── seeders/
│   └── main.dart
├── bin/
│   └── server.dart
├── config/
│   ├── app.dart
│   ├── development/
│   │   └── logging.json
│   └── production/
├── lang/
│   ├── ar/
│   └── en/
├── public/
│   ├── index.html
│   └── assets/
├── resources/
│   └── views/
├── routes/
│   ├── socket.dart
│   └── web.dart
├── storage/
│   ├── app/
│   ├── framework/
│   │   ├── cache/
│   │   ├── sessions/
│   │   └── views/
│   └── logs/
├── tests/
├── .env
├── .env.example
├── .gitignore
├── Dockerfile
├── docker-compose.yml
├── pubspec.yaml
└── README.md`

const appStructureCode = `lib/app/
├── http/
│   ├── controllers/
│   │   ├── home_controller.dart
│   │   ├── user_controller.dart
│   │   └── api/
│   │       └── v1/
│   │           └── auth_controller.dart
│   └── middleware/
│       ├── auth_middleware.dart
│       ├── cors_middleware.dart
│       └── logging_middleware.dart
├── models/
│   ├── user.dart
│   └── post.dart
├── providers/
│   ├── app_service_provider.dart
│   ├── event_service_provider.dart
│   └── scheduler_service_provider.dart
├── jobs/
│   ├── send_welcome_email_job.dart
│   ├── process_image_job.dart
│   └── email/
│       └── send_notification_job.dart
├── listeners/
│   └── user_registered_listener.dart`

const routesExample = `// routes/web.dart
import 'package:khadem/khadem_dart.dart';
import '../lib/app/http/controllers/home_controller.dart';
import '../lib/core/kernel.dart';

void registerRoutes(Server server) {
  // Register global middlewares
  server.useMiddlewares(Kernel.middlewares);

  // API Routes
  server.group(
    prefix: '/api',
    middleware: [],
    routes: (router) async {
      router.get('/hello', HomeController.index);
      router.get('/welcome', HomeController.welcome);
      router.get('/stream', HomeController.stream);
    },
  );

  // Serve static files
  server.serveStatic();
}

// routes/socket.dart
import 'package:khadem/khadem_dart.dart';

void registerSocketRoutes(SocketServer socketServer) {
  socketServer.on('chat:message', (socket, data) {
    // Handle chat messages
    socketServer.broadcast('chat:message', data);
  });

  socketServer.on('user:join', (socket, data) {
    // Handle user joining
    socket.broadcast('user:joined', data);
  });
}`

const configExample = `// config/app.dart
import 'package:khadem/khadem_dart.dart';

class AppConfig {
  static final env = Khadem.env;

  static Map<String, Map<String, dynamic>> get configs => {
    'database': {
      'driver': env.getOrDefault('DB_CONNECTION', 'mysql'),
      'host': env.getOrDefault('DB_HOST', 'localhost'),
      'port': env.getInt('DB_PORT'),
      'database': env.get('DB_DATABASE'),
      'username': env.get('DB_USERNAME'),
      'password': env.get('DB_PASSWORD'),
      'run_migrations': true,
      'run_seeders': false,
    },
    'cache': {
      'default': 'hybrid',
      'drivers': {
        'file': {'driver': 'file', 'path': 'storage/cache'},
        'memory': {'driver': 'memory'},
        'hybrid': {'driver': 'hybrid', 'path': 'storage/cache'},
      },
    },
    'queue': {
      'driver': 'file',
      'run_in_background': true,
      'auto_start': true,
    },
    'auth': {
      'default': 'users',
      'guards': {
        'users': {'driver': 'token', 'provider': 'users'},
      },
      'providers': {
        'users': {
          'table': 'users',
          'primary_key': 'id',
          'fields': ['email'],
        },
      },
    },
  };
}`

const kernelExample = `// lib/core/kernel.dart
import 'package:khadem/khadem_dart.dart';
import '../app/providers/app_service_provider.dart';
import '../app/providers/event_service_provider.dart';
import '../app/providers/scheduler_service_provider.dart';
import '../../config/app.dart';
import '../database/migrations/migrations.dart';

class Kernel {
  Kernel._();

  static List<ServiceProvider> get coreProviders => [
    QueueServiceProvider(),
    AuthServiceProvider(),
    DatabaseServiceProvider(),
  ];

  static List<ServiceProvider> get applicationProviders => [
    AppServiceProvider(),
    EventServiceProvider(),
    SchedulerServiceProvider(),
  ];

  static List<ServiceProvider> get allProviders => [
    ...coreProviders,
    ...applicationProviders,
  ];

  static List<Middleware> get middlewares => [
    CorsMiddleware(),
    LoggingMiddleware(),
    SetLocaleMiddleware(),
  ];

  static final Map<String, Map<String, dynamic>> configs = AppConfig.configs;
  static List<MigrationFile> get migrations => migrationsFiles;

  static Future<void> bootstrap() async {
    await Khadem.registerCoreServices();
    Khadem.register(allProviders);
    Khadem.loadConfigs(configs);
    await Khadem.boot();

    if (configs['database']?['run_migrations'] == true) {
      await Khadem.migrator.upAll(migrations);
    }
  }
}`

const databaseStructureCode = `lib/database/
├── migrations/
│   ├── 001_create_users_table.dart
│   ├── 002_create_posts_table.dart
│   ├── 003_add_user_id_to_posts.dart
│   └── migrations.dart
└── seeders/
    ├── database_seeder.dart
    ├── user_seeder.dart
    └── post_seeder.dart`

const storageStructureCode = `storage/
├── app/
│   ├── public/
│   └── private/
├── framework/
│   ├── cache/
│   │   ├── data/
│   │   └── views/
│   ├── sessions/
│   └── views/
└── logs/
    ├── khadem.log
    └── error.log`

const mainEntryPoint = `// lib/main.dart
import 'dart:async';
import 'dart:io';
import 'package:khadem/khadem_dart.dart';
import 'lib/core/kernel.dart';
import '../routes/socket.dart';
import '../routes/web.dart';

Future<void> main(List<String> args) async {
  if (_isSnapshotBuild()) return;

  final container = Khadem.container;
  await Kernel.bootstrap();

  final port = _extractPort(args) ?? Khadem.env.getInt("APP_PORT", defaultValue: 8080);

  await Future.wait([
    _startHttpServer(port, container),
    _startSocketServer(container, Khadem.socket),
  ]);
}

bool _isSnapshotBuild() => Platform.environment.containsKey('KHADIM_JIT_TRAINING');

Future _startHttpServer(int port, ContainerInterface container) async {
  final server = Server();
  registerRoutes(server);
  server.setInitializer(() async {
    registerRoutes(server);
    await server.start(port: port);
  });
  await server.reload();
}

Future<void> _startSocketServer(container, manager) async {
  final socketPort = Khadem.env.getInt("SOCKET_PORT", defaultValue: 8080);
  final socketServer = SocketServer(socketPort, manager: manager);
  registerSocketRoutes(socketServer);
  await socketServer.start();
}

int? _extractPort(List<String> args) {
  final portIndex = args.indexOf('--port');
  if (portIndex != -1 && args.length > portIndex + 1) {
    return int.tryParse(args[portIndex + 1]);
  }
  return null;
}`

const serverEntryPoint = `// lib/main.dart
import '../lib/main.dart' as app;

Future<void> main(List<String> args) async {
  await app.main(args);
}`

const pubspecExample = `name: my_api
description: A new Khadem Dart project.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  khadem:
    path: ../khadem

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.6`

const envExample = `# Application Configuration
APP_NAME=MyFirstAPI
APP_ENV=development
APP_PORT=8080
APP_LOCALE=en

# Database Configuration (MySQL)
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=my_first_api_db
DB_USERNAME=root
DB_PASSWORD=

# JWT Authentication
JWT_SECRET="your-super-secret-jwt-key-here"
JWT_ACCESS_EXPIRY_MINUTES=60
JWT_REFRESH_EXPIRY_DAYS=30`

const gitignoreExample = `# Dart
.dart_tool/
.packages
pubspec.lock

# Environment variables
.env
.env.local
.env.*.local

# Build outputs
build/
.dart_tool/

# IDEs
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/

# Temporary files
tmp/
temp/

# Test coverage
coverage/

# Khadem specific
storage/framework/cache/*
storage/framework/sessions/*
storage/framework/views/*
storage/logs/*`

const customStructureExample = `my_api/
├── lib/
│   ├── app/
│   │   ├── http/
│   │   ├── services/
│   │   │   ├── payment/
│   │   │   │   ├── stripe_service.dart
│   │   │   │   └── paypal_service.dart
│   │   │   └── notification/
│   │   │       ├── email_service.dart
│   │   │       └── sms_service.dart
│   │   └── repositories/
│   │       ├── user_repository.dart
│   │       └── post_repository.dart
│   ├── core/
│   └── database/
├── config/
│   ├── payment.dart
│   └── notification.dart
└── tests/
    ├── unit/
    │   ├── services/
    │   └── repositories/
    └── feature/
        ├── payment/
        └── notification/`
</script>